# Generated by Django 4.0.2 on 2024-01-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fantaformula',
        ),
        migrations.AddField(
            model_name='user',
            name='fanta',
            field=models.IntegerField(default='3'),
        ),
    ]
