# Generated by Django 4.0.2 on 2022-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0002_formula_punti_utente_moto_punti_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fantaformula',
            field=models.BooleanField(default=True),
        ),
    ]
