# Generated by Django 4.0.2 on 2024-01-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0002_remove_user_fantaformula_user_fanta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula_team',
            name='piloti',
        ),
        migrations.RemoveField(
            model_name='moto_team',
            name='piloti',
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fantamotori.formula_team'),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fantamotori.formula_team'),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fantamotori.moto_team'),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fantamotori.moto_team'),
        ),
        migrations.AlterField(
            model_name='formula_punti',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moto_punti',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
