# Generated by Django 4.0.2 on 2022-03-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0003_user_fantaformula'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto_punti',
            name='differenza',
            field=models.IntegerField(default='0'),
        ),
    ]
