# Generated by Django 4.0.2 on 2022-03-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0004_moto_punti_differenza'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula_punti',
            name='differenza',
            field=models.IntegerField(default='0'),
        ),
    ]
