# Generated by Django 4.0.2 on 2022-03-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0005_formula_punti_differenza'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula_formazione',
            name='username',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='username',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='formula_punti',
            name='username',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='username',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='username',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='moto_formazione',
            name='username',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='username',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='moto_punti',
            name='username',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='username',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='username',
            field=models.TextField(default='a'),
        ),
    ]
