# Generated by Django 5.0.1 on 2025-02-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0006_remove_moto_piloti_gara23_remove_moto_team_gara23_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula_piloti',
            name='gara25',
        ),
        migrations.RemoveField(
            model_name='formula_piloti',
            name='gara26',
        ),
        migrations.RemoveField(
            model_name='formula_team',
            name='gara25',
        ),
        migrations.RemoveField(
            model_name='formula_team',
            name='gara26',
        ),
        migrations.RemoveField(
            model_name='formula_teammanager',
            name='gara25',
        ),
        migrations.RemoveField(
            model_name='formula_teammanager',
            name='gara26',
        ),
    ]
