# Generated by Django 4.0.2 on 2022-03-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0009_formula_formazione_vittoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto_formazione',
            name='vittoria',
            field=models.BooleanField(default=False),
        ),
    ]
