# Generated by Django 4.0.2 on 2022-03-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0011_remove_moto_formazione_vittoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto_formazione',
            name='capitano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capitan', to='fantamotori.moto_piloti'),
        ),
    ]
