# Generated by Django 4.0.2 on 2022-03-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0012_moto_formazione_capitano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto_formazione',
            name='p_totali',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moto_formazione',
            name='risultato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
