# Generated by Django 4.0.2 on 2022-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0013_alter_moto_formazione_p_totali_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula_formazione',
            name='vittoria',
        ),
        migrations.AddField(
            model_name='formula_formazione',
            name='risultato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formula_formazione',
            name='p_totali',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
