# Generated by Django 4.0.2 on 2022-03-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0014_remove_formula_formazione_vittoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula_formazione',
            name='teammanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fantamotori.formula_teammanager'),
        ),
        migrations.AlterField(
            model_name='moto_formazione',
            name='teammanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fantamotori.moto_teammanager'),
        ),
    ]
