# Generated by Django 4.0.2 on 2022-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0016_moto_passato'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto_piloti',
            name='gara1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
