# Generated by Django 4.0.2 on 2022-11-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0017_moto_piloti_gara1_moto_piloti_gara10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto_piloti',
            name='totale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='totale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='totale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
