# Generated by Django 4.0.2 on 2022-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0019_rename_gara1_moto_piloti_gara01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto_giornata',
            name='calcolata',
            field=models.BooleanField(default=False),
        ),
    ]
