# Generated by Django 4.0.2 on 2022-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0020_moto_giornata_calcolata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto_piloti',
            name='totale',
        ),
        migrations.RemoveField(
            model_name='moto_team',
            name='totale',
        ),
        migrations.RemoveField(
            model_name='moto_teammanager',
            name='totale',
        ),
        migrations.AddField(
            model_name='formula_giornata',
            name='f3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara03',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara04',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara05',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara06',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara07',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara08',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara09',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara03',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara04',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara05',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara06',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara07',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara08',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara09',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara03',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara04',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara05',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara06',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara07',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara08',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara09',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara22',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
