# Generated by Django 4.0.2 on 2022-12-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0021_remove_moto_piloti_totale_remove_moto_team_totale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula_piloti',
            name='totale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='totale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='totale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='totale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='totale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='totale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
