# Generated by Django 4.0.2 on 2022-12-01 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0022_formula_piloti_totale_formula_team_totale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula_passato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_pscontri', models.IntegerField(default='0')),
                ('ex_pgenerali', models.IntegerField(default='0')),
                ('ex_differenza', models.IntegerField(default='0')),
                ('ex_username', models.TextField(default='a')),
                ('ex_utente', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
