# Generated by Django 4.0.2 on 2022-12-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0023_formula_passato'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula_giornata',
            name='sprint',
            field=models.BooleanField(default=False),
        ),
    ]
