# Generated by Django 4.0.2 on 2022-12-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0024_formula_giornata_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula_giornata',
            name='calcolata',
            field=models.BooleanField(default=False),
        ),
    ]
