# Generated by Django 4.0.2 on 2022-12-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0025_formula_giornata_calcolata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula_giornata',
            name='f3',
        ),
        migrations.AddField(
            model_name='moto_giornata',
            name='sbk',
            field=models.BooleanField(default=False),
        ),
    ]
