# Generated by Django 4.0.2 on 2022-12-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0026_remove_formula_giornata_f3_moto_giornata_sbk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rimosso',
            field=models.BooleanField(default=False),
        ),
    ]
