# Generated by Django 4.0.2 on 2022-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0027_user_rimosso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto_punti',
            name='utente',
            field=models.TextField(),
        ),
    ]
