# Generated by Django 4.0.2 on 2022-12-07 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0028_alter_moto_punti_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto_passato',
            name='ex_utente',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='moto_punti',
            name='utente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
