# Generated by Django 4.0.2 on 2022-12-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0030_remove_moto_passato_ex_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula_passato',
            name='ex_utente',
        ),
    ]
