# Generated by Django 4.0.2 on 2022-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0031_remove_formula_passato_ex_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula_piloti',
            name='gara23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_piloti',
            name='gara24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_team',
            name='gara24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula_teammanager',
            name='gara24',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
