# Generated by Django 4.0.2 on 2023-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0032_formula_piloti_gara23_formula_piloti_gara24_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula_piloti',
            name='gara24',
        ),
        migrations.RemoveField(
            model_name='formula_team',
            name='gara24',
        ),
        migrations.RemoveField(
            model_name='formula_teammanager',
            name='gara24',
        ),
        migrations.AddField(
            model_name='moto_piloti',
            name='gara23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_team',
            name='gara23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto_teammanager',
            name='gara23',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
