# Generated by Django 4.0.2 on 2023-03-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamotori', '0033_remove_formula_piloti_gara24_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula_piloti',
            name='totale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formula_team',
            name='totale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formula_teammanager',
            name='totale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moto_piloti',
            name='totale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moto_team',
            name='totale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moto_teammanager',
            name='totale',
            field=models.IntegerField(default=0),
        ),
    ]
